@startuml name SmartHouse
title Тёплый дом TOBE Container Diagram (Спринт 3 Задание 2)

top to bottom direction

!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(amdin, "Admin", "Управляет типами устройств")
System(smartHouseDevice, "SmartHouse Device", "Устройство и/или Датчик(Сенсор)")

Container_Boundary(smartHouse, "SmartHouse System") {
  Container(Users, "Users", "C#/java, Postgres/Mongo", "Управление пользователями + авторизация")
  Container(UIApiGateway, "UIApiGateway", "Nginx", "Балансирует, аутентифицирует, представляет API")
  Container(DeviceDictionary, "DeviceDictionary", "C#, Mongo", "Спраовчник типов устройств")
  Container(DataBus, "DataBus", "kafka", "Интеграция сервисов")
  Container(DeviceDictionaryDb, "DeviceDictionaryDb", "MongoDb", "Хранилище типов устройств")

}

Container(DeviceDictionary, "DeviceDictionary", "C#, Postgres", "Спраовчник типов устройств") {
  Component(DictionaryController, "DictionaryController", "Управление справочником Типов устройств")
}




' begin UIApiGateway
Rel(UIApiGateway, Users, "Проверяет JWT")
Rel(amdin, UIApiGateway, "Авторизуется, получает JWT")
Rel(amdin, UIApiGateway, "Управляет Справочником Устройств")

' end UIApiGateway


'begin DeviceDictionary
Rel(UIApiGateway, DictionaryController, "Управляет Справочником Устройств")
Rel(DictionaryController, DeviceDictionaryDb, "Получение списка устройств")
Rel(DictionaryController, DeviceDictionaryDb, "Получение карточки устройства")
Rel(DictionaryController, DeviceDictionaryDb, "Установка  карточки устройства")
Rel(DictionaryController, DeviceDictionaryDb, "Управление статусом типа устройства")

Rel(DictionaryController, DataBus, "Действия пользователя")
Rel(DictionaryController, DataBus, "Создание карточки устройства")
Rel(DictionaryController, DataBus, "Изменение статуса карточки устройства")
'end DeviceDictionary





@enduml