@startuml name SmartHouse
title Тёплый дом TOBE Container Diagram (Спринт 3 Задание 2)

top to bottom direction

!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

System(smartHouse, "SmartHouse System", "Система Теплый дом")



Container_Boundary(smartHouse, "SmartHouse System") {
  'ELK не подходит для долгосрочного хранения - требуется исследовать решение
  Container(HistoryStorage, "HistoryStorage", "DWH?/ELK", "Хранение историчестких данных, витрины")
  Container(DataBus, "DataBus", "kafka", "Интеграция сервисов")
}

Container(HistoryStorage, "DWH") {
  Component(logstash, "logstash", "logstash", "Обработка сообщений")
  Component(Elasticsearch, "Elasticsearch", "Elasticsearch", "Хранение данных")
  Component(Kibana , "Kibana", "Kibana", "Отображение оперативных данных")
}

Rel(logstash, DataBus, "Получает сообщения для устройств")
Rel(logstash, DataBus, "Получает сообщения от устройств")
Rel(logstash, DataBus, "Получает авторизацию пользователя")
Rel(logstash, DataBus, "Получает действия пользователя")

Rel(logstash, Elasticsearch, "Передает данные")


Rel(Kibana, Elasticsearch, "ПРолучает данные")

@enduml