@startuml name SmartHouse
title Тёплый дом TOBE Context Diagram (Спринт 3 Задание 2)

top to bottom direction

!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Полдьзователь системы")
Person(amdin, "Admin", "Управляет типами устройств")
System(smartHouse, "SmartHouse System", "Система Теплый дом")
'System(sensor, "SmartHouse sensor", "Сенсор системы")
System(smartHouseDevice, "SmartHouse Device", "Устройство и/или Датчик(Сенсор)")
System_Ext(partners, "Partners", "Партнеры")


'Rel(partners, smartHouse, "Получение документации публичного API")
Rel(partners, smartHouseDevice, "Прошивка устройств/преднастройка (стандартные протоколы)")
'Rel(partners, sensor, "Прошивка устройств/преднастройка (стандартные протоколы)")
'Rel(partners, smartHouse, "TOBE2: регистрация новых типов устройств")

Rel(partners, user, "Продажа устройств")
Rel(partners, user, "Осблуживание устройств")

'Rel(user, sensor, "Установка датчиков(сенсоров)")
Rel(user, smartHouseDevice, "Установка устройств")

Rel(user, smartHouse, "Регистрируется/управяет учеткой (стандартные протоколы)")
Rel(user, smartHouse, "Регистрирует устройства/управляет списком устройств")
Rel(user, smartHouse, "Управляет устройствами")
Rel(user, smartHouse, "Просматривает показания (телеметрия)")
Rel(user, smartHouse, "Настраивает скрипты поведения (сценарии работы)")

Rel(amdin, smartHouse, "Управляет справочником типов устрйоств")

' Rel(admin, smartHouse, "Регистрирует новые устройства")
' Rel(admin, smartHouse, "Удаляет устройства")
' Rel(engineer, sensor, "Устанавливает/ремонтирует/снимает")
' Rel(engineer, heatingSystem, "Устанавливает/ремонтирует/снимает")


Rel(smartHouseDevice, smartHouse, "Установка соединения (статус Online, KeepAlive)")
Rel(smartHouseDevice, smartHouse, "Получает конфигурацию")
Rel(smartHouseDevice, smartHouse, "Передает показания")

@enduml