@startuml name SmartHouse
title Тёплый дом TOBE Container Diagram (Спринт 3 Задание 2)

top to bottom direction

!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Полдьзователь системы")
System(smartHouseDevice, "SmartHouse Device", "Устройство и/или Датчик(Сенсор)")

Container_Boundary(smartHouse, "SmartHouse System") {
  Container(Users, "Users", "C#/java, Postgres/Mongo", "Управление пользователями + авторизация")
  Container(UIApiGateway, "UIApiGateway", "Nginx", "Балансирует, аутентифицирует, представляет API")
  Container(DataBus, "DataBus", "kafka", "Интеграция сервисов")
  Container(UsersCache, "UsersCache", "Redis", "Кэш")
  Container(UsersDb, "UsersDb", "Mongo", "Хранилище пользователей")
}

Container(Users, "Users", "C#/java, Postgres/Mongo") {
  Component(AuthController, "AuthController", "Авторизация и аутентификация")
  Component(UserController, "UserController", "Управление профилем пользователей")
}



' begin UIApiGateway
Rel(user, UIApiGateway, "Регистрируется/управяет своей УЗ")
Rel(user, UIApiGateway, "Авторизуется, получает JWT")
Rel(user, UIApiGateway, "Регистрирует/управляет профилем")
Rel(user, UIApiGateway, "Просматривает показания (телеметрия)")
Rel(user, UIApiGateway, "Настраивает скрипты поведения (сценарии работы)")
Rel(UIApiGateway, AuthController, "Проверяет JWT")
' end UIApiGateway

'begin Users
Rel(UIApiGateway, UserController, "Регистрируется/управяет своей УЗ")
Rel(UserController, UsersCache, "Получение сессии")
Rel(UserController, UsersCache, "Передача сессии")
Rel(UserController, UsersDb, "Получение/Установка карточки пользователя")
Rel(UserController, UsersDb, "Получение/Установка прав пользователя")
Rel(UserController, DataBus, "События действий пользователя")


Rel(UIApiGateway, AuthController, "Авторизуется, получает JWT")
Rel(AuthController, UsersCache, "Передача Сесиия пользователя, выданные JWT")
Rel(AuthController, UsersCache, "Проверка выданных JWT, получение сессии")
Rel(AuthController, UsersDb, "Получение Статуса, Логина, Пароля (Хэш)")
Rel(AuthController, UsersDb, "Создание пользователя")
Rel(AuthController, UsersDb, "Блокировка пользователя")
Rel(AuthController, DataBus, "События авторизации, изменения статуса")
'end users



@enduml